- name: Copy MongoDB YUM repo file
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Replace Listen address in MongoDB Configuration file
  ansible.builtin.replace:
    path:  /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    state: restarted

- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
